[package]
name = "javascriptcore-sys"
version = "0.1.42"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Raw bindings to the JavaScriptCore framework."
build = "build.rs"

[target.'cfg(target_os = "linux")'.build-dependencies]
pkg-config = "0.3.9"
